### ISSUE TITLE
az keyvault list assumes non-table output

### ISSUE THREAD

**Issue by swgriffith** [microsoft/confidential-container-demos#8]
The grep used in the key vault lookup assumes the user has not set their default azure cli output to 'table'. Table formatted output does not match the grep lookup value and the user will get a false "Azure akv resource endpoint doesn't exist." error message. 

You can recreate this issue by running 'az configure', set the default output format to 'table' and then run the setup-key.sh

Should update the script to use 'az keyvault list -o json' to ensure consistent behavior.

**Comment by BryceDFisher** [comment]
Thank you for your contribution!
